/*
 * Copyright (c) 2026 Standard Applied Intelligence Labs
 * SPDX-License-Identifier: MIT
 */

package ai.singlr.sail.engine;

import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.TimeoutException;

/**
 * Installs {@code ~/.sail/bin/sail-stop-gate}, the combined {@code Stop}-hook script for
 * sail-launched agent sessions. Claude Code runs the hooks of a matcher group in parallel, so
 * gating and lifecycle publishing must live in one script: on each stop attempt the gate decides
 * first, then publishes {@code agent_session_stopped} (allow) or {@code agent_stop_nudged} (block)
 * through {@link SailEventHelper} — the pipeline never sees a stop that did not happen. The
 * terminal publish is best-effort and advisory only: the agent lane refuses terminal session types
 * (a run must never mark itself finished and release its reservation), so run completion comes
 * solely from the watcher's verified exit, with the missed-stop reconciler as the rescue lane.
 *
 * <p>Sessions that write to a spec branch are gated: they carry a non-blank {@code SAIL_RUN_ID} —
 * build-role dispatches, and the review pipeline's fix lane (which exports the run id but no {@code
 * SAIL_SPEC_ID}, so this gate blocks its premature stops while its publishes stay silent). Reviewer
 * sessions carry no run id — a reviewer must be free to stop without committing — and ad-hoc {@code
 * sail agent start} or engineer sessions carry none either, so all of them keep the old
 * publish-and-allow behavior.
 *
 * <p>The dirty/unpushed/PR checks are scoped to the run's spec repos — read from {@code repos} in
 * the run's own session file, {@code ~/.sail/runs/<runId>/agent-session.json}, which dispatch
 * stamps with the spec's resolved repos. A repo the spec does not target (dirtied by a concurrent
 * or previous dispatch in the shared container) never nudges this run. When the session lists no
 * repos — a missing session file or a non-dispatch launch — every workspace repo is checked, the
 * prior behavior. A {@code room}-role run (the wake lane's chat sessions, marked by {@code role} in
 * the session file) skips the git protocol entirely: a chat owns no repos, so a dirty tree in the
 * shared container is never its concern — but it keeps the room last-look below, so a human reply
 * racing the chat's end is still guaranteed a reading.
 *
 * <p>Beyond the git protocol, the gate takes one last look at the spec room: the run's undelivered
 * messages ({@code GET /v1/run/messages}, run-credential-scoped) block the stop with their bodies
 * as the reason, so a human reply that raced the turn's end is guaranteed a reading — the relay
 * covers the middle of the run, this covers its edge. The exact message ids shown are acknowledged
 * ({@code POST delivered=<ids>}) before the marker is spent or the block emitted; a failed
 * acknowledgement drops the room block entirely, leaving the messages undelivered for the relay or
 * a later stop, so delivery state and what the agent saw can never disagree. When the inbox reports
 * {@code has_more}, the block reason tells the agent to read the rest of the room — the remainder
 * also reaches it through the relay on its next tool call.
 *
 * <p>Each concern blocks at most once per run — the git protocol drops {@code stop-nudged}, the
 * room last-look its own {@code stop-room-nudged} marker under {@code ~/.sail/runs/&lt;runId&gt;/}
 * — so the agent keeps its contractual right to stop-and-report failure and a message that arrives
 * after a git nudge still gets its one block, while neither a storm of messages nor a dirty tree
 * can wedge a run. It fails open on every unexpected condition (unparseable stdin, missing git or
 * python3, unwritable marker, absent socket, failed acknowledgement, hook timeout): a
 * wrongly-jailed agent is strictly worse than a premature stop. stdout is reserved for the
 * hook-protocol block JSON, which is fed the reason over stdin so even maximum-size room messages
 * never trip the kernel's per-argument exec limit.
 *
 * <p>The script is CLI-agnostic — stdin JSON in, block JSON out, marker-file loop guard — with
 * Claude Code's {@code stop_hook_active} honored belt-and-braces when present, so Codex hook config
 * can wire the same script unchanged.
 */
public final class SailStopGate {

  /** Container-side path of the gate script. */
  public static final String SCRIPT_PATH = "/home/dev/.sail/bin/sail-stop-gate";

  /**
   * Explicit {@code Stop}-hook timeout in seconds. A timed-out hook is killed and never blocks, so
   * a hung {@code git status} (or anything else) fails open by construction.
   */
  public static final int HOOK_TIMEOUT_SECONDS = 15;

  private static final String SCRIPT =
      """
      #!/bin/sh
      # Generated by sail. Combined Stop hook: readiness gate + lifecycle publisher.
      # Claude Code runs a matcher group's hooks in parallel, so deciding and
      # publishing are sequenced inside this one script, never via hook ordering.
      # Gated sessions (non-blank SAIL_RUN_ID) must have every workspace repo
      # clean, pushed, and behind a PR before the turn may end, and get one last
      # look at the spec room: the run's undelivered messages block the stop with
      # their bodies as the reason. The exact ids shown are acknowledged before
      # the marker is spent or the block emitted; a failed ack drops the room
      # block and leaves the messages undelivered for the relay or a later stop.
      # Each concern blocks at most once via its own marker file (stop-nudged for
      # the git protocol, stop-room-nudged for the room), so a message that
      # arrives after a git nudge still gets its one block and neither concern
      # can wedge a run. stdout is reserved for the hook-protocol block JSON.
      # A room-role run (role "room" in its session file) skips the git protocol
      # entirely — a chat owns no repos and must never be nudged about other
      # runs' trees — while keeping the room last-look.
      # Any unexpected condition fails open: this gate is a nudge, not a jail.
      set -u

      SAIL_HOME="${HOME:-/home/dev}"
      EVENT_HELPER="$SAIL_HOME/.sail/bin/sail-event.sh"
      WORKSPACE="$SAIL_HOME/workspace"
      RUNS_DIR="$SAIL_HOME/.sail/runs"
      SOCKET="__SAIL_API_SOCKET__"

      publish() {
        if [ -x "$EVENT_HELPER" ]; then
          "$EVENT_HELPER" "$@" >/dev/null 2>&1 || true
        fi
      }

      allow() {
        publish agent_session_stopped
        exit 0
      }

      INPUT="$(cat 2>/dev/null || true)"
      RUN_ID="${SAIL_RUN_ID:-}"

      [ -n "$RUN_ID" ] || allow
      SESSION="$RUNS_DIR/$RUN_ID/agent-session.json"
      command -v git >/dev/null 2>&1 || allow
      command -v python3 >/dev/null 2>&1 || allow

      STOP_HOOK_ACTIVE="$(printf '%s' "$INPUT" | python3 -c '
      import json, sys
      try:
          payload = json.load(sys.stdin)
      except Exception:
          print("unparseable")
      else:
          print("yes" if payload.get("stop_hook_active") else "no")
      ' 2>/dev/null || true)"
      [ "$STOP_HOOK_ACTIVE" = "no" ] || allow

      GIT_MARKER="$RUNS_DIR/$RUN_ID/stop-nudged"
      ROOM_MARKER="$RUNS_DIR/$RUN_ID/stop-room-nudged"
      if [ -f "$GIT_MARKER" ] && [ -f "$ROOM_MARKER" ]; then
        allow
      fi

      RUN_ROLE="$(python3 -c '
      import json, sys
      try:
          print(json.load(open(sys.argv[1])).get("role") or "")
      except Exception:
          pass
      ' "$SESSION" 2>/dev/null || true)"

      REASONS=""
      if [ "$RUN_ROLE" != "room" ] && [ ! -f "$GIT_MARKER" ]; then
        REPOS="$(python3 -c '
      import json, sys
      try:
          repos = json.load(open(sys.argv[1])).get("repos") or []
      except Exception:
          sys.exit(0)
      for r in repos:
          print(r)
      ' "$SESSION" 2>/dev/null || true)"

        in_scope() {
          [ -n "$REPOS" ] || return 0
          printf '%s\n' "$REPOS" | grep -qxF "$1"
        }

        note() {
          if [ -n "$REASONS" ]; then
            REASONS="$REASONS; $1"
          else
            REASONS="$1"
          fi
        }

        for repo_dir in "$WORKSPACE"/*/; do
          [ -e "$repo_dir.git" ] || continue
          repo="$(basename "$repo_dir")"
          in_scope "$repo" || continue
          dirty="$(git -C "$repo_dir" status --porcelain 2>/dev/null || true)"
          [ -z "$dirty" ] || note "commit your work in $repo (the worktree is dirty)"
          branch="$(git -C "$repo_dir" symbolic-ref --short -q HEAD 2>/dev/null || true)"
          [ -n "$branch" ] || continue
          if upstream="$(git -C "$repo_dir" rev-parse --abbrev-ref "$branch@{upstream}" 2>/dev/null)"; then
            ahead="$(git -C "$repo_dir" rev-list --count "$upstream..$branch" 2>/dev/null || echo 0)"
            [ "$ahead" = "0" ] || note "push $branch in $repo ($ahead commits ahead of $upstream)"
          else
            note "push $branch in $repo (no upstream; git push -u origin $branch)"
            continue
          fi
          default="$(git -C "$repo_dir" symbolic-ref -q --short refs/remotes/origin/HEAD 2>/dev/null || true)"
          case "$branch" in
            "${default#origin/}"|main|master) continue ;;
          esac
          command -v gh >/dev/null 2>&1 || continue
          GH_TIMEOUT=""
          command -v timeout >/dev/null 2>&1 && GH_TIMEOUT="timeout 5"
          pr_err="$( (cd "$repo_dir" && $GH_TIMEOUT gh pr view "$branch" --json state >/dev/null) 2>&1 || true)"
          case "$pr_err" in
            *"no pull requests found"*) note "open a pull request for $branch in $repo" ;;
          esac
        done
      fi

      ROOM_REASON=""
      ROOM_IDS=""
      ROOM_MORE=""
      if [ ! -f "$ROOM_MARKER" ] && [ -n "${SAIL_RUN_CREDENTIAL:-}" ] && [ -S "$SOCKET" ] \\
        && command -v curl >/dev/null 2>&1; then
        INBOX="$(curl --silent --max-time 5 \\
          --unix-socket "$SOCKET" \\
          -H "Authorization: Bearer ${SAIL_RUN_CREDENTIAL}" \\
          http://sail/v1/run/messages 2>/dev/null || true)"
        if [ -n "$INBOX" ]; then
          ROOM_IDS="$(printf '%s' "$INBOX" | python3 -c '
      import json, sys
      try:
          messages = json.load(sys.stdin).get("messages") or []
          print(",".join(m["id"] for m in messages if m.get("id")))
      except Exception:
          pass
      ' 2>/dev/null || true)"
        fi
        if [ -n "$ROOM_IDS" ]; then
          ROOM_MORE="$(printf '%s' "$INBOX" | python3 -c '
      import json, sys
      try:
          print("yes" if json.load(sys.stdin).get("has_more") else "")
      except Exception:
          pass
      ' 2>/dev/null || true)"
          ROOM_REASON="$(printf '%s' "$INBOX" | python3 -c '
      import json, sys
      try:
          messages = json.load(sys.stdin).get("messages") or []
          print("; ".join(
              "from %s: %s" % (m.get("author", "unknown"), " ".join((m.get("body") or "").split()))
              for m in messages))
      except Exception:
          pass
      ' 2>/dev/null || true)"
        fi
        if [ -n "$ROOM_REASON" ]; then
          ACK="$(curl --silent --output /dev/null --write-out '%{http_code}' --max-time 5 \\
            --unix-socket "$SOCKET" \\
            -H "Authorization: Bearer ${SAIL_RUN_CREDENTIAL}" \\
            -X POST --data-urlencode "delivered=$ROOM_IDS" \\
            http://sail/v1/run/messages 2>/dev/null || true)"
          if [ "$ACK" = "200" ]; then
            mkdir -p "$RUNS_DIR/$RUN_ID" 2>/dev/null || true
            : > "$ROOM_MARKER" 2>/dev/null || true
          else
            ROOM_REASON=""
          fi
        fi
      fi

      if [ -n "$REASONS" ]; then
        if mkdir -p "$RUNS_DIR/$RUN_ID" 2>/dev/null && : > "$GIT_MARKER" 2>/dev/null; then :; else
          REASONS=""
        fi
      fi
      if [ -z "$REASONS" ] && [ -z "$ROOM_REASON" ]; then
        allow
      fi

      REASON=""
      if [ -n "$REASONS" ]; then
        REASON="Not ready to stop: $REASONS. Finish the dispatch protocol (commit, push, open the PR, watch its checks to green) before ending the turn."
      fi
      if [ -n "$ROOM_REASON" ]; then
        REASON="$REASON${REASON:+ }Room messages arrived while you were working — $ROOM_REASON."
        if [ -n "$ROOM_MORE" ]; then
          REASON="$REASON More messages are waiting beyond this batch: read the room with spec comments <spec-id> before ending the turn."
        fi
        REASON="$REASON Address or acknowledge them (reply with spec comment) before ending the turn."
      fi
      REASON="$REASON If you are genuinely blocked, say so explicitly and stop again."
      publish agent_stop_nudged "$(printf '%.2000s' "$REASON")"
      printf '%s' "$REASON" | python3 -c 'import json, sys; print(json.dumps({"decision": "block", "reason": sys.stdin.read()}))'
      exit 0
      """;

  private final ShellExec shell;

  public SailStopGate(ShellExec shell) {
    this.shell = Objects.requireNonNull(shell, "shell");
  }

  /** Returns the script content that {@link #install(String)} writes. Pure function. */
  public static String scriptContent() {
    return SCRIPT.replace("__SAIL_API_SOCKET__", SailPaths.apiSocketContainerPath().toString());
  }

  /**
   * Idempotently installs the gate script at {@link #SCRIPT_PATH} inside the given container, chmod
   * 0755, owned by the dev user.
   */
  public void install(String container) throws IOException, InterruptedException, TimeoutException {
    NameValidator.requireValidProjectName(container);

    var mkdir =
        shell.exec(
            ContainerExec.asDevUser(container, List.of("mkdir", "-p", SailEventHelper.SCRIPT_DIR)));
    if (!mkdir.ok()) {
      throw new IOException(
          "Failed to create "
              + SailEventHelper.SCRIPT_DIR
              + " in "
              + container
              + ": "
              + mkdir.stderr());
    }

    var write =
        shell.exec(
            ContainerExec.asDevUser(
                container,
                List.of(
                    "bash",
                    "-c",
                    "printf '%s' \"$1\" > \"$2\" && chmod 0755 \"$2\"",
                    "bash",
                    scriptContent(),
                    SCRIPT_PATH)));
    if (!write.ok()) {
      throw new IOException(
          "Failed to install " + SCRIPT_PATH + " in " + container + ": " + write.stderr());
    }
  }
}
