/*
 * Copyright (c) 2026 Standard Applied Intelligence Labs
 * SPDX-License-Identifier: MIT
 */

package ai.singlr.sail.engine;

import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.TimeoutException;

/**
 * Installs and locates {@code ~/.sail/bin/sail-event.sh}, the per-container shell helper that agent
 * hooks invoke to publish events to the host {@code sail-api} over the bind-mounted Unix socket at
 * {@link SailPaths#apiSocketContainerPath()}.
 *
 * <p>The script is intentionally tiny and dependency-free: pure bash + curl, no jq, no python. It
 * builds a minimal {@link ai.singlr.sail.api.Event}-shaped JSON body and POSTs it best-effort —
 * failures (socket missing, sail-api restarting) are swallowed so a transient host hiccup never
 * blocks an agent.
 */
public final class SailEventHelper {

  /** Container-side path of the helper script. */
  public static final String SCRIPT_PATH = "/home/dev/.sail/bin/sail-event.sh";

  /** Container-side parent directory of {@link #SCRIPT_PATH}. */
  public static final String SCRIPT_DIR = "/home/dev/.sail/bin";

  private static final String SCRIPT =
      """
      #!/usr/bin/env bash
      # Generated by sail. Posts one lifecycle event to the sail-api Unix socket.
      #   Args: <event-type> [reason]
      # The optional reason lands in data.reason, sanitized to keep the
      # hand-built JSON valid (quotes, backslashes, control chars dropped).
      # Spec attribution flows in via SAIL_SPEC_ID env var (set by sail at launch);
      # absent or blank means an engineer-initiated session — skip silently so
      # ad-hoc 'claude' invocations never pollute the spec event bus.
      # The run credential (SAIL_RUN_CREDENTIAL, injected at launch) authenticates the
      # request; the server stamps authorship from it, so the agent field here is advisory.
      set -eu

      EVENT_TYPE="${1:?event type required}"
      REASON="$(printf '%s' "${2:-}" | tr -d '\\\\"\\000-\\037')"
      SPEC_ID="${SAIL_SPEC_ID:-}"
      if [ -z "$SPEC_ID" ]; then
        exit 0
      fi
      AGENT="${SAIL_AGENT:-claude-code}"
      RUN_ID="${SAIL_RUN_ID:-}"
      CREDENTIAL="${SAIL_RUN_CREDENTIAL:-}"
      PROJECT="$(hostname)"
      HOST="$(hostname)"
      TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
      SOCKET="__SAIL_API_SOCKET__"

      if [ ! -S "$SOCKET" ]; then
        exit 0
      fi

      FIELDS=""
      if [ -n "$RUN_ID" ]; then
        FIELDS="\\"run_id\\":\\"$RUN_ID\\""
      fi
      if [ -n "$REASON" ]; then
        FIELDS="$FIELDS${FIELDS:+,}\\"reason\\":\\"$REASON\\""
      fi
      DATA="{$FIELDS}"
      BODY="{\\"v\\":1,\\"ts\\":\\"$TS\\",\\"project\\":\\"$PROJECT\\",\\"spec\\":\\"$SPEC_ID\\",\\"type\\":\\"$EVENT_TYPE\\",\\"agent\\":\\"$AGENT\\",\\"host\\":\\"$HOST\\",\\"data\\":$DATA}"

      curl --silent --max-time 5 \\
        --unix-socket "$SOCKET" \\
        -H 'Content-Type: application/json' \\
        -H "Authorization: Bearer $CREDENTIAL" \\
        -X POST -d "$BODY" \\
        http://sail/v1/events >/dev/null 2>&1 || true
      """;

  private final ShellExec shell;

  public SailEventHelper(ShellExec shell) {
    this.shell = Objects.requireNonNull(shell, "shell");
  }

  /** Returns the script content that {@link #install(String)} writes. Pure function. */
  public static String scriptContent() {
    return SCRIPT.replace("__SAIL_API_SOCKET__", SailPaths.apiSocketContainerPath().toString());
  }

  /**
   * Idempotently installs the helper script at {@link #SCRIPT_PATH} inside the given container,
   * chmod 0755, owned by the dev user.
   */
  public void install(String container) throws IOException, InterruptedException, TimeoutException {
    NameValidator.requireValidProjectName(container);

    var mkdir = shell.exec(ContainerExec.asDevUser(container, List.of("mkdir", "-p", SCRIPT_DIR)));
    if (!mkdir.ok()) {
      throw new IOException(
          "Failed to create " + SCRIPT_DIR + " in " + container + ": " + mkdir.stderr());
    }

    var write =
        shell.exec(
            ContainerExec.asDevUser(
                container,
                List.of(
                    "bash",
                    "-c",
                    "printf '%s' \"$1\" > \"$2\" && chmod 0755 \"$2\"",
                    "bash",
                    scriptContent(),
                    SCRIPT_PATH)));
    if (!write.ok()) {
      throw new IOException(
          "Failed to install " + SCRIPT_PATH + " in " + container + ": " + write.stderr());
    }
  }
}
