/*
 * Copyright (c) 2026 Standard Applied Intelligence Labs
 * SPDX-License-Identifier: MIT
 */

package ai.singlr.sail.engine;

import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.TimeoutException;

/**
 * Installs {@code ~/.sail/bin/sail-stop-gate}, the combined {@code Stop}-hook script for
 * sail-launched agent sessions. Claude Code runs the hooks of a matcher group in parallel, so
 * gating and lifecycle publishing must live in one script: on each stop attempt the gate decides
 * first, then publishes {@code agent_session_stopped} (allow) or {@code agent_stop_nudged} (block)
 * through {@link SailEventHelper} — the pipeline never sees a stop that did not happen. The
 * terminal publish is best-effort and advisory only: the agent lane refuses terminal session types
 * (a run must never mark itself finished and release its reservation), so run completion comes
 * solely from the watcher's verified exit, with the missed-stop reconciler as the rescue lane.
 *
 * <p>Sessions that write to a spec branch are gated: they carry a non-blank {@code SAIL_RUN_ID} —
 * build-role dispatches, and the review pipeline's fix lane (which exports the run id but no {@code
 * SAIL_SPEC_ID}, so this gate blocks its premature stops while its publishes stay silent). Reviewer
 * sessions carry no run id — a reviewer must be free to stop without committing — and ad-hoc {@code
 * sail agent start} or engineer sessions carry none either, so all of them keep the old
 * publish-and-allow behavior.
 *
 * <p>The dirty/unpushed/PR checks are scoped to the run's spec repos — read from {@code repos} in
 * the run's own session file, {@code ~/.sail/runs/<runId>/agent-session.json}, which dispatch
 * stamps with the spec's resolved repos. A repo the spec does not target (dirtied by a concurrent
 * or previous dispatch in the shared container) never nudges this run. When the session lists no
 * repos — a missing session file or a non-dispatch launch — every workspace repo is checked, the
 * prior behavior.
 *
 * <p>The gate blocks at most once per run — the first block drops a marker file under {@code
 * ~/.sail/runs/&lt;runId&gt;/} — so the agent keeps its contractual right to stop-and-report
 * failure: the second stop always wins. It fails open on every unexpected condition (unparseable
 * stdin, missing git or python3, unwritable marker, hook timeout): a wrongly-jailed agent is
 * strictly worse than a premature stop. stdout is reserved for the hook-protocol block JSON.
 *
 * <p>The script is CLI-agnostic — stdin JSON in, block JSON out, marker-file loop guard — with
 * Claude Code's {@code stop_hook_active} honored belt-and-braces when present, so Codex hook config
 * can wire the same script unchanged.
 */
public final class SailStopGate {

  /** Container-side path of the gate script. */
  public static final String SCRIPT_PATH = "/home/dev/.sail/bin/sail-stop-gate";

  /**
   * Marker {@link ai.singlr.sail.engine.ContainerSailSetup} greps for to detect a gate script
   * written before the session file moved into the run directory, so a stale container is refreshed
   * on the next dispatch. A literal substring of the run-scoped session assignment, chosen without
   * {@code $} so the probe's shell never expands it.
   */
  public static final String RUN_SESSION_MARKER = "RUN_ID/agent-session.json";

  /**
   * Explicit {@code Stop}-hook timeout in seconds. A timed-out hook is killed and never blocks, so
   * a hung {@code git status} (or anything else) fails open by construction.
   */
  public static final int HOOK_TIMEOUT_SECONDS = 15;

  private static final String SCRIPT =
      """
      #!/bin/sh
      # Generated by sail. Combined Stop hook: readiness gate + lifecycle publisher.
      # Claude Code runs a matcher group's hooks in parallel, so deciding and
      # publishing are sequenced inside this one script, never via hook ordering.
      # Gated sessions (non-blank SAIL_RUN_ID) must have every workspace repo
      # clean, pushed, and behind a PR before the turn may end; the first
      # premature stop is blocked with concrete next actions and publishes
      # agent_stop_nudged, every later stop passes (marker file loop guard).
      # stdout is reserved for the hook-protocol block JSON. Any unexpected
      # condition fails open: this gate is a nudge, not a jail.
      set -u

      SAIL_HOME="${HOME:-/home/dev}"
      EVENT_HELPER="$SAIL_HOME/.sail/bin/sail-event.sh"
      WORKSPACE="$SAIL_HOME/workspace"
      RUNS_DIR="$SAIL_HOME/.sail/runs"

      publish() {
        if [ -x "$EVENT_HELPER" ]; then
          "$EVENT_HELPER" "$@" >/dev/null 2>&1 || true
        fi
      }

      allow() {
        publish agent_session_stopped
        exit 0
      }

      INPUT="$(cat 2>/dev/null || true)"
      RUN_ID="${SAIL_RUN_ID:-}"

      [ -n "$RUN_ID" ] || allow
      SESSION="$RUNS_DIR/$RUN_ID/agent-session.json"
      command -v git >/dev/null 2>&1 || allow
      command -v python3 >/dev/null 2>&1 || allow

      STOP_HOOK_ACTIVE="$(printf '%s' "$INPUT" | python3 -c '
      import json, sys
      try:
          payload = json.load(sys.stdin)
      except Exception:
          print("unparseable")
      else:
          print("yes" if payload.get("stop_hook_active") else "no")
      ' 2>/dev/null || true)"
      [ "$STOP_HOOK_ACTIVE" = "no" ] || allow

      MARKER="$RUNS_DIR/$RUN_ID/stop-nudged"
      [ ! -f "$MARKER" ] || allow

      REPOS="$(python3 -c '
      import json, sys
      try:
          repos = json.load(open(sys.argv[1])).get("repos") or []
      except Exception:
          sys.exit(0)
      for r in repos:
          print(r)
      ' "$SESSION" 2>/dev/null || true)"

      in_scope() {
        [ -n "$REPOS" ] || return 0
        printf '%s\n' "$REPOS" | grep -qxF "$1"
      }

      REASONS=""
      note() {
        if [ -n "$REASONS" ]; then
          REASONS="$REASONS; $1"
        else
          REASONS="$1"
        fi
      }

      for repo_dir in "$WORKSPACE"/*/; do
        [ -e "$repo_dir.git" ] || continue
        repo="$(basename "$repo_dir")"
        in_scope "$repo" || continue
        dirty="$(git -C "$repo_dir" status --porcelain 2>/dev/null || true)"
        [ -z "$dirty" ] || note "commit your work in $repo (the worktree is dirty)"
        branch="$(git -C "$repo_dir" symbolic-ref --short -q HEAD 2>/dev/null || true)"
        [ -n "$branch" ] || continue
        if upstream="$(git -C "$repo_dir" rev-parse --abbrev-ref "$branch@{upstream}" 2>/dev/null)"; then
          ahead="$(git -C "$repo_dir" rev-list --count "$upstream..$branch" 2>/dev/null || echo 0)"
          [ "$ahead" = "0" ] || note "push $branch in $repo ($ahead commits ahead of $upstream)"
        else
          note "push $branch in $repo (no upstream; git push -u origin $branch)"
          continue
        fi
        default="$(git -C "$repo_dir" symbolic-ref -q --short refs/remotes/origin/HEAD 2>/dev/null || true)"
        case "$branch" in
          "${default#origin/}"|main|master) continue ;;
        esac
        command -v gh >/dev/null 2>&1 || continue
        GH_TIMEOUT=""
        command -v timeout >/dev/null 2>&1 && GH_TIMEOUT="timeout 5"
        pr_err="$( (cd "$repo_dir" && $GH_TIMEOUT gh pr view "$branch" --json state >/dev/null) 2>&1 || true)"
        case "$pr_err" in
          *"no pull requests found"*) note "open a pull request for $branch in $repo" ;;
        esac
      done

      [ -n "$REASONS" ] || allow

      mkdir -p "$RUNS_DIR/$RUN_ID" 2>/dev/null || allow
      : > "$MARKER" 2>/dev/null || allow

      REASON="Not ready to stop: $REASONS. Finish the dispatch protocol (commit, push, open the PR, watch its checks to green) before ending the turn. If you are genuinely blocked, say so explicitly and stop again."
      publish agent_stop_nudged "$REASON"
      python3 -c 'import json, sys; print(json.dumps({"decision": "block", "reason": sys.argv[1]}))' "$REASON"
      exit 0
      """;

  private final ShellExec shell;

  public SailStopGate(ShellExec shell) {
    this.shell = Objects.requireNonNull(shell, "shell");
  }

  /** Returns the script content that {@link #install(String)} writes. Pure function. */
  public static String scriptContent() {
    return SCRIPT;
  }

  /**
   * Idempotently installs the gate script at {@link #SCRIPT_PATH} inside the given container, chmod
   * 0755, owned by the dev user.
   */
  public void install(String container) throws IOException, InterruptedException, TimeoutException {
    NameValidator.requireValidProjectName(container);

    var mkdir =
        shell.exec(
            ContainerExec.asDevUser(container, List.of("mkdir", "-p", SailEventHelper.SCRIPT_DIR)));
    if (!mkdir.ok()) {
      throw new IOException(
          "Failed to create "
              + SailEventHelper.SCRIPT_DIR
              + " in "
              + container
              + ": "
              + mkdir.stderr());
    }

    var write =
        shell.exec(
            ContainerExec.asDevUser(
                container,
                List.of(
                    "bash",
                    "-c",
                    "printf '%s' \"$1\" > \"$2\" && chmod 0755 \"$2\"",
                    "bash",
                    scriptContent(),
                    SCRIPT_PATH)));
    if (!write.ok()) {
      throw new IOException(
          "Failed to install " + SCRIPT_PATH + " in " + container + ": " + write.stderr());
    }
  }
}
