/*
 * Copyright (c) 2026 Standard Applied Intelligence Labs
 * SPDX-License-Identifier: MIT
 */

package ai.singlr.sail.engine;

import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.TimeoutException;

/**
 * Installs {@code ~/.sail/bin/sail-session-report}, the {@code SessionStart} hook that reports the
 * agent conversation's identity to its run row: the hook payload's {@code session_id}, {@code
 * transcript_path}, and start {@code source} (startup/resume/clear/compact) POST to {@code
 * /v1/run/session} over the run-credential socket lane, making the conversation a first-class,
 * resumable object — {@code sail agent attach} rebuilds the exact resume argv from it, and a wake
 * can reopen the run with its context intact.
 *
 * <p>The report gates on {@code SAIL_RUN_ID} alone — the stop gate's env contract — so the fix lane
 * (run id, no {@code SAIL_SPEC_ID}) reports its resumable conversation too, and reviewer or
 * engineer sessions, which carry no run id, are inert by construction. The server resolves run →
 * spec from the run credential, and last write wins there: a resume, clear, or compact restart
 * simply re-reports the new conversation, so the row always names the invocation a human would want
 * to attach to. Both CLIs feed the same script — Claude Code and Codex SessionStart payloads carry
 * {@code session_id} and {@code transcript_path} under the same names (verified against the current
 * Codex hooks docs; Codex sources are startup/resume/clear, without compact).
 *
 * <p>Fail-open and cheap by design: any missing tool, absent socket, malformed payload, or API
 * error exits 0 silently — a session report must never block or fail an agent. One {@code python3}
 * parse and at most one bounded {@code curl} per session start.
 */
public final class SailSessionReport {

  /** Container-side path of the session report script. */
  public static final String SCRIPT_PATH = "/home/dev/.sail/bin/sail-session-report";

  /**
   * Explicit hook timeout in seconds; a hung report is killed and the session continues. Holds
   * margin beyond the single 5-second {@code curl} deadline.
   */
  public static final int HOOK_TIMEOUT_SECONDS = 10;

  private static final String SCRIPT =
      """
      #!/bin/sh
      # Generated by sail. SessionStart hook: reports the conversation's
      # session_id, transcript_path, and start source from the hook payload to
      # the run row over the run-credential socket lane, so the run's exact
      # conversation is resumable later (sail agent attach). Gates on
      # SAIL_RUN_ID like the stop gate, so only sail-launched gated runs
      # (dispatch and the review fix lane) ever report; reviewer and engineer
      # sessions are inert. Last write wins server-side: a resume, clear, or
      # compact restart simply re-reports the new conversation.
      # Every unexpected condition exits 0 silently: a session report must
      # never block or fail an agent. Stdin is drained before any guard can
      # exit, so the hook writer never takes an EPIPE from an early return.
      set -u

      PAYLOAD="$(cat 2>/dev/null || true)"

      RUN_ID="${SAIL_RUN_ID:-}"
      [ -n "$RUN_ID" ] || exit 0
      CREDENTIAL="${SAIL_RUN_CREDENTIAL:-}"
      [ -n "$CREDENTIAL" ] || exit 0
      SOCKET="__SAIL_API_SOCKET__"
      [ -S "$SOCKET" ] || exit 0
      command -v curl >/dev/null 2>&1 || exit 0
      command -v python3 >/dev/null 2>&1 || exit 0

      BODY="$(printf '%s' "$PAYLOAD" | python3 -c '
      import json, sys, urllib.parse
      try:
          payload = json.load(sys.stdin)
          session = payload.get("session_id") or ""
          if not session:
              sys.exit(0)
          fields = {"session_id": session}
          if payload.get("source"):
              fields["source"] = payload["source"]
          if payload.get("transcript_path"):
              fields["transcript_path"] = payload["transcript_path"]
          print(urllib.parse.urlencode(fields))
      except Exception:
          pass
      ' 2>/dev/null || true)"
      [ -n "$BODY" ] || exit 0

      curl --silent --output /dev/null --max-time 5 \\
        --unix-socket "$SOCKET" \\
        -H "Authorization: Bearer $CREDENTIAL" \\
        -X POST --data "$BODY" \\
        http://sail/v1/run/session 2>/dev/null || true
      exit 0
      """;

  private final ShellExec shell;

  public SailSessionReport(ShellExec shell) {
    this.shell = Objects.requireNonNull(shell, "shell");
  }

  /** Returns the script content that {@link #install(String)} writes. Pure function. */
  public static String scriptContent() {
    return SCRIPT.replace("__SAIL_API_SOCKET__", SailPaths.apiSocketContainerPath().toString());
  }

  /**
   * Idempotently installs the report script at {@link #SCRIPT_PATH} inside the given container,
   * chmod 0755, owned by the dev user.
   */
  public void install(String container) throws IOException, InterruptedException, TimeoutException {
    NameValidator.requireValidProjectName(container);

    var mkdir =
        shell.exec(
            ContainerExec.asDevUser(container, List.of("mkdir", "-p", SailEventHelper.SCRIPT_DIR)));
    if (!mkdir.ok()) {
      throw new IOException(
          "Failed to create "
              + SailEventHelper.SCRIPT_DIR
              + " in "
              + container
              + ": "
              + mkdir.stderr());
    }

    var write =
        shell.exec(
            ContainerExec.asDevUser(
                container,
                List.of(
                    "bash",
                    "-c",
                    "printf '%s' \"$1\" > \"$2\" && chmod 0755 \"$2\"",
                    "bash",
                    scriptContent(),
                    SCRIPT_PATH)));
    if (!write.ok()) {
      throw new IOException(
          "Failed to install " + SCRIPT_PATH + " in " + container + ": " + write.stderr());
    }
  }
}
