/*
 * Copyright (c) 2026 Standard Applied Intelligence Labs
 * SPDX-License-Identifier: MIT
 */

package ai.singlr.sail.engine;

import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.TimeoutException;

/**
 * Installs {@code ~/.sail/bin/sail-room-relay}, the {@code PostToolUse} hook that delivers
 * spec-room messages to a live run between tool calls — the steer seam: a human reply posted
 * mid-run lands in the model's context before its next reasoning step instead of an inbox nobody
 * reads. Registered beside the heartbeat hook in the one hooks layer of both CLIs; the heartbeat
 * prints nothing, so stdout stays the relay's.
 *
 * <p>The relay gates on {@code SAIL_RUN_ID} alone — the stop gate's env contract — so the fix lane
 * (run id, no {@code SAIL_SPEC_ID}) gets delivery while its event publishes stay silent, and
 * reviewer or engineer sessions, which carry no run id, are inert by construction. It asks {@code
 * GET /v1/run/messages} for messages newer than its run's delivery watermark; the server resolves
 * run → spec from the run credential, so the script never needs a spec id. Fresh messages are
 * acknowledged first ({@code POST delivered=<latest>}, advancing the watermark so the stop gate
 * agrees on what was seen) and then emitted as {@code hookSpecificOutput.additionalContext}, framed
 * per message as {@code [Room message from <author>, arrived while you were working]: <body>}.
 *
 * <p>Fail-open and cheap by design: any missing tool, absent socket, API error, or failed
 * acknowledgement exits 0 silently — a chatty room or a down server must never break a build — and
 * an interval stamp under the run directory skips the API round-trip entirely unless {@value
 * #CHECK_INTERVAL_SECONDS} seconds have passed since the last check, so a busy agent costs one
 * {@code date} and one {@code cat} per tool call.
 */
public final class SailRoomRelay {

  /** Container-side path of the relay script. */
  public static final String SCRIPT_PATH = "/home/dev/.sail/bin/sail-room-relay";

  /** Explicit hook timeout in seconds; a hung relay is killed and the build continues. */
  public static final int HOOK_TIMEOUT_SECONDS = 10;

  /** Minimum seconds between API checks — the cost ceiling of a very busy agent. */
  public static final int CHECK_INTERVAL_SECONDS = 15;

  private static final String SCRIPT =
      """
      #!/bin/sh
      # Generated by sail. PostToolUse hook: delivers spec-room messages that
      # arrived mid-run into the agent's context via additionalContext. Gates on
      # SAIL_RUN_ID like the stop gate, so only sail-launched gated runs (dispatch
      # and the review fix lane) ever see a delivery; reviewer and engineer
      # sessions are inert. Messages are acknowledged (watermark advance) before
      # they are emitted, so the stop gate never re-delivers what landed here.
      # Every unexpected condition exits 0 silently: delivery is best-effort and
      # must never break a build. An interval stamp under the run dir keeps the
      # relay to at most one API round-trip per __CHECK_INTERVAL__ seconds.
      set -u

      RUN_ID="${SAIL_RUN_ID:-}"
      [ -n "$RUN_ID" ] || exit 0
      CREDENTIAL="${SAIL_RUN_CREDENTIAL:-}"
      [ -n "$CREDENTIAL" ] || exit 0
      SOCKET="__SAIL_API_SOCKET__"
      [ -S "$SOCKET" ] || exit 0
      command -v curl >/dev/null 2>&1 || exit 0
      command -v python3 >/dev/null 2>&1 || exit 0

      SAIL_HOME="${HOME:-/home/dev}"
      RUN_DIR="$SAIL_HOME/.sail/runs/$RUN_ID"
      STAMP="$RUN_DIR/room-relay-checked"
      NOW="$(date +%s 2>/dev/null || echo 0)"
      LAST="$(cat "$STAMP" 2>/dev/null || echo 0)"
      case "$LAST" in '' | *[!0-9]*) LAST=0 ;; esac
      [ $((NOW - LAST)) -ge __CHECK_INTERVAL__ ] || exit 0
      mkdir -p "$RUN_DIR" 2>/dev/null || exit 0
      printf '%s' "$NOW" > "$STAMP" 2>/dev/null || exit 0

      INBOX="$(curl --silent --max-time 5 \\
        --unix-socket "$SOCKET" \\
        -H "Authorization: Bearer $CREDENTIAL" \\
        http://sail/v1/run/messages 2>/dev/null || true)"
      [ -n "$INBOX" ] || exit 0

      LATEST="$(printf '%s' "$INBOX" | python3 -c '
      import json, sys
      try:
          print(json.load(sys.stdin).get("latest") or "")
      except Exception:
          pass
      ' 2>/dev/null || true)"
      [ -n "$LATEST" ] || exit 0

      ACK="$(curl --silent --output /dev/null --write-out "%{http_code}" --max-time 5 \\
        --unix-socket "$SOCKET" \\
        -H "Authorization: Bearer $CREDENTIAL" \\
        -X POST --data-urlencode "delivered=$LATEST" \\
        http://sail/v1/run/messages 2>/dev/null || true)"
      [ "$ACK" = "200" ] || exit 0

      printf '%s' "$INBOX" | python3 -c '
      import json, sys
      try:
          messages = json.load(sys.stdin).get("messages") or []
          if not messages:
              sys.exit(0)
          context = "\\n\\n".join(
              "[Room message from %s, arrived while you were working]: %s"
              % (m.get("author", "unknown"), m.get("body", ""))
              for m in messages)
          print(json.dumps({"hookSpecificOutput": {
              "hookEventName": "PostToolUse",
              "additionalContext": context}}))
      except Exception:
          pass
      ' 2>/dev/null || true
      exit 0
      """;

  private final ShellExec shell;

  public SailRoomRelay(ShellExec shell) {
    this.shell = Objects.requireNonNull(shell, "shell");
  }

  /** Returns the script content that {@link #install(String)} writes. Pure function. */
  public static String scriptContent() {
    return SCRIPT
        .replace("__SAIL_API_SOCKET__", SailPaths.apiSocketContainerPath().toString())
        .replace("__CHECK_INTERVAL__", Integer.toString(CHECK_INTERVAL_SECONDS));
  }

  /**
   * Idempotently installs the relay script at {@link #SCRIPT_PATH} inside the given container,
   * chmod 0755, owned by the dev user.
   */
  public void install(String container) throws IOException, InterruptedException, TimeoutException {
    NameValidator.requireValidProjectName(container);

    var mkdir =
        shell.exec(
            ContainerExec.asDevUser(container, List.of("mkdir", "-p", SailEventHelper.SCRIPT_DIR)));
    if (!mkdir.ok()) {
      throw new IOException(
          "Failed to create "
              + SailEventHelper.SCRIPT_DIR
              + " in "
              + container
              + ": "
              + mkdir.stderr());
    }

    var write =
        shell.exec(
            ContainerExec.asDevUser(
                container,
                List.of(
                    "bash",
                    "-c",
                    "printf '%s' \"$1\" > \"$2\" && chmod 0755 \"$2\"",
                    "bash",
                    scriptContent(),
                    SCRIPT_PATH)));
    if (!write.ok()) {
      throw new IOException(
          "Failed to install " + SCRIPT_PATH + " in " + container + ": " + write.stderr());
    }
  }
}
