/*
 * Copyright (c) 2026 Standard Applied Intelligence Labs
 * SPDX-License-Identifier: MIT
 */

package ai.singlr.sail.engine;

import java.io.IOException;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.TimeoutException;

/**
 * Installs {@code ~/.sail/bin/spec}, the per-container shell helper an agent uses to manage this
 * project's specs in the shared Sail database. It talks to the host {@code sail-api} over the same
 * bind-mounted Unix socket the event helper uses ({@code /run/sail/api.sock}) — so an agent never
 * needs the {@code sail} binary, a token, or files on disk; the database is the single source of
 * truth and {@code sail sync} replicates it to every other box.
 *
 * <p>The script is intentionally tiny and dependency-free: pure bash + curl, no jq, no python. It
 * derives the project from the container hostname (the convention the event helper already relies
 * on) and lets {@code curl --data-urlencode} escape titles and markdown bodies, so the shell never
 * hand-builds JSON.
 */
public final class SpecCliHelper {

  /** Container-side path of the helper script. */
  public static final String SCRIPT_PATH = "/home/dev/.sail/bin/spec";

  /** Container-side parent directory of {@link #SCRIPT_PATH}. */
  public static final String SCRIPT_DIR = "/home/dev/.sail/bin";

  private static final String SCRIPT =
      """
      #!/usr/bin/env bash
      # Generated by sail. Manage this project's specs in the shared Sail database
      # over the bind-mounted API socket. Dependency-free: bash + curl, no jq.
      set -euo pipefail

      SOCKET="/run/sail/api.sock"
      BASE="http://sail/v1/specs"
      PROJECT="$(hostname)"
      ACTOR="${SAIL_ACTOR:-agent}"

      die() { echo "spec: $*" >&2; exit 1; }
      [ -S "$SOCKET" ] || die "API socket not found at $SOCKET (is the project running?)"

      api() {
        curl --silent --show-error --fail-with-body --max-time 20 --unix-socket "$SOCKET" "$@"
      }

      # Maps --flag values from "$@" into curl --data-urlencode fields. Knows the spec fields;
      # --body-file/--plan-file are read and url-encoded from a file by curl itself.
      collect_fields() {
        FIELDS=(--data-urlencode "actor=$ACTOR")
        while [ $# -gt 0 ]; do
          case "$1" in
            --title)            FIELDS+=(--data-urlencode "title=$2"); shift 2;;
            --status)           FIELDS+=(--data-urlencode "status=$2"); shift 2;;
            --assignee)         FIELDS+=(--data-urlencode "assignee=$2"); shift 2;;
            --agent)            FIELDS+=(--data-urlencode "agent=$2"); shift 2;;
            --model)            FIELDS+=(--data-urlencode "model=$2"); shift 2;;
            --reasoning-effort) FIELDS+=(--data-urlencode "reasoning_effort=$2"); shift 2;;
            --branch)           FIELDS+=(--data-urlencode "branch=$2"); shift 2;;
            --priority)         FIELDS+=(--data-urlencode "priority=$2"); shift 2;;
            --depends-on)       FIELDS+=(--data-urlencode "depends_on=$2"); shift 2;;
            --repos)            FIELDS+=(--data-urlencode "repos=$2"); shift 2;;
            --body-file)        FIELDS+=(--data-urlencode "body@$2"); shift 2;;
            --plan-file)        FIELDS+=(--data-urlencode "plan@$2"); shift 2;;
            --id)               FIELDS+=(--data-urlencode "id=$2"); shift 2;;
            --project)          PROJECT="$2"; shift 2;;
            --actor)            ACTOR="$2"; shift 2;;
            *) die "unknown option: $1";;
          esac
        done
      }

      usage() {
        cat >&2 <<'USAGE'
      spec — manage this project's specs (stored in the Sail database, synced across devboxes)

        spec board                         show the kanban summary
        spec list [--status S] [--assignee me] [--search Q]
        spec show <id>
        spec create --id <id> --title <title> [--body-file F] [--status pending]
                    [--depends-on a,b] [--repos a,b] [--agent A] [--model M]
                    [--reasoning-effort none|low|medium|high|xhigh] [--priority N] [--plan-file F]
        spec update <id> [--status S] [--title T] [--depends-on a,b] [--repos a,b] [...]
        spec content <id> --body-file F [--plan-file F]   revise the body
        spec archive <id>
      USAGE
        exit "${1:-0}"
      }

      cmd="${1:-}"; [ $# -gt 0 ] && shift || true
      case "$cmd" in
        board)
          api -G --data-urlencode "project=$PROJECT" "$BASE/board";;
        list)
          collect_fields "$@"
          api -G --data-urlencode "project=$PROJECT" "${FIELDS[@]}" "$BASE";;
        show)
          [ $# -ge 1 ] || die "show needs a spec id"
          api "$BASE/$1";;
        create)
          collect_fields "$@"
          api -X POST --data-urlencode "project=$PROJECT" "${FIELDS[@]}" "$BASE";;
        update)
          [ $# -ge 1 ] || die "update needs a spec id"
          id="$1"; shift
          collect_fields "$@"
          api -X PUT "${FIELDS[@]}" "$BASE/$id";;
        content)
          [ $# -ge 1 ] || die "content needs a spec id"
          id="$1"; shift
          collect_fields "$@"
          api -X PUT "${FIELDS[@]}" "$BASE/$id/content";;
        archive)
          [ $# -ge 1 ] || die "archive needs a spec id"
          api -X PUT --data-urlencode "actor=$ACTOR" --data-urlencode "status=archived" "$BASE/$1";;
        ""|-h|--help) usage 0;;
        *) die "unknown command: $cmd (try 'spec --help')";;
      esac
      """;

  private final ShellExec shell;

  public SpecCliHelper(ShellExec shell) {
    this.shell = Objects.requireNonNull(shell, "shell");
  }

  /** Returns the script content that {@link #install(String)} writes. Pure function. */
  public static String scriptContent() {
    return SCRIPT;
  }

  /**
   * Idempotently installs the helper script at {@link #SCRIPT_PATH} inside the given container,
   * chmod 0755, owned by the dev user.
   */
  public void install(String container) throws IOException, InterruptedException, TimeoutException {
    NameValidator.requireValidProjectName(container);

    var mkdir = shell.exec(ContainerExec.asDevUser(container, List.of("mkdir", "-p", SCRIPT_DIR)));
    if (!mkdir.ok()) {
      throw new IOException(
          "Failed to create " + SCRIPT_DIR + " in " + container + ": " + mkdir.stderr());
    }

    var write =
        shell.exec(
            ContainerExec.asDevUser(
                container,
                List.of(
                    "bash",
                    "-c",
                    "printf '%s' \"$1\" > \"$2\" && chmod 0755 \"$2\"",
                    "bash",
                    SCRIPT,
                    SCRIPT_PATH)));
    if (!write.ok()) {
      throw new IOException(
          "Failed to install " + SCRIPT_PATH + " in " + container + ": " + write.stderr());
    }
  }
}
