/*
 * Copyright (c) 2026 Standard Applied Intelligence Labs
 * SPDX-License-Identifier: MIT
 */

package ai.singlr.sail.engine;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import ai.singlr.sail.config.HostYaml;
import ai.singlr.sail.config.SailYaml;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class ProjectProvisionerTest {

  @TempDir Path tempDir;

  private static SailYaml fullConfig() {
    return new SailYaml(
        "acme-health",
        "Acme Health Platform",
        new SailYaml.Resources(4, "12GB", "150GB"),
        "ubuntu/24.04",
        List.of("postgresql-client-16"),
        new SailYaml.Runtimes(25, "22", null),
        null,
        null,
        Map.of(
            "postgres", new SailYaml.Service("postgres:16", List.of(5432), Map.of(), null, null)),
        Map.of("app", new SailYaml.Process("java -jar app.jar", ".")),
        new SailYaml.Agent(
            "claude-code", true, "sail/", true, null, Map.of(), null, null, null, null, null),
        null,
        new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA... alice@laptop")));
  }

  private static SailYaml minimalConfig() {
    return new SailYaml(
        "simple",
        "Simple project",
        new SailYaml.Resources(2, "4GB", "50GB"),
        "ubuntu/24.04",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null);
  }

  private static HostYaml hostYaml() {
    return new HostYaml(
        "zfs",
        "devpool",
        "/dev/sdb",
        "incusbr0",
        "singlr-base",
        "ubuntu/24.04",
        "6.3",
        null,
        "2026-02-18T00:00:00Z");
  }

  /**
   * Shell that succeeds for all 18 provisioning steps. Patterns must match the command strings
   * generated by ProjectProvisioner for fullConfig(). Steps 11-13 (git, maven, repos) are
   * auto-skipped because fullConfig() has null git/repos/maven. Step 16 (agent tools) is
   * auto-skipped because fullConfig() has install=null.
   */
  private ScriptedShellExecutor allSuccessShell() {
    return new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
        .onFail("incus info acme-health", "not found")
        .onOk("incus launch")
        .onOk("ip -4 addr show")
        .onFail("id dev", "no such user")
        .onOk("useradd")
        .onFail("which podman", "")
        .onFail("test -f /etc/profile.d/testcontainers.sh", "")
        .onFail("dpkg -s temurin-25-jdk", "not installed")
        .onOk("echo $VERSION_CODENAME", "noble")
        .onFail("node --version", "not found")
        .onFail("podman container inspect", "no such container")
        .onFail("crontab -l", "no crontab for dev")
        .onOk("mktemp", "/tmp/sail-crontab.test123\n");
  }

  /** Shell for minimalConfig — no runtimes, no services, no SSH, no git/repos. */
  private ScriptedShellExecutor minimalSuccessShell() {
    return new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
        .onFail("incus info simple", "not found")
        .onOk("incus launch")
        .onOk("ip -4 addr show")
        .onFail("which podman", "")
        .onFail("test -f /etc/profile.d/testcontainers.sh", "")
        .onFail("crontab -l", "no crontab for dev")
        .onOk("mktemp", "/tmp/sail-crontab.test123\n");
  }

  private ProvisionTracker<ProjectPhase> tracker() {
    return new ProvisionTracker<>(
        ProjectPhase.class, tempDir.resolve("provision-state.yaml"), false);
  }

  private ProvisionTracker<ProjectPhase> dryRunTracker() {
    return new ProvisionTracker<>(
        ProjectPhase.class, tempDir.resolve("provision-state.yaml"), true);
  }

  @Test
  void fullProvisionCompletesAllSteps() throws Exception {
    var shell = allSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertEquals(35, steps.size());
    assertTrue(steps.stream().anyMatch(s -> s.contains("done:1/")));
    assertTrue(steps.stream().anyMatch(s -> s.contains("done:20/")));
  }

  @Test
  void nullListenerDoesNotThrow() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    assertDoesNotThrow(() -> provisioner.provision(fullConfig(), hostYaml(), null, null));
  }

  @Test
  void stateFileCleanedUpOnSuccess() throws Exception {
    var shell = allSuccessShell();
    var stateFile = tempDir.resolve("provision-state.yaml");
    var tracker = new ProvisionTracker<>(ProjectPhase.class, stateFile, false);
    var provisioner = new ProjectProvisioner(shell, tracker, null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertFalse(
        java.nio.file.Files.exists(stateFile),
        "State file should be deleted on successful completion");
  }

  @Test
  void resumeFromNetworkReadySkipsFirstThreeSteps() throws Exception {
    var stateFile = tempDir.resolve("provision-state.yaml");
    var setupTracker = new ProvisionTracker<>(ProjectPhase.class, stateFile, false);
    setupTracker.load();
    setupTracker.advance(ProjectPhase.RESOURCE_LIMITS_SET);

    var shell = allSuccessShell();
    var steps = new ArrayList<String>();
    var tracker = new ProvisionTracker<>(ProjectPhase.class, stateFile, false);
    var provisioner = new ProjectProvisioner(shell, tracker, new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertEquals(32, steps.size());
    assertTrue(steps.get(0).contains("skipped:1/"));
    assertTrue(steps.get(1).contains("skipped:2/"));
    assertTrue(steps.get(2).contains("skipped:3/"));
    assertTrue(steps.get(3).contains("step:4/"));
  }

  @Test
  void resumeFromPackagesSkipsFirstFiveSteps() throws Exception {
    var stateFile = tempDir.resolve("provision-state.yaml");
    var setupTracker = new ProvisionTracker<>(ProjectPhase.class, stateFile, false);
    setupTracker.load();
    setupTracker.advance(ProjectPhase.PACKAGES_INSTALLED);

    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab");
    var steps = new ArrayList<String>();
    var tracker = new ProvisionTracker<>(ProjectPhase.class, stateFile, false);
    var provisioner = new ProjectProvisioner(shell, tracker, new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertEquals(30, steps.size());
    assertTrue(steps.get(0).contains("skipped:1/"));
    assertTrue(steps.get(4).contains("skipped:5/"));
    assertTrue(steps.get(5).contains("step:6/"));
  }

  @Test
  void resumeFromSshConfiguredRunsNewSteps() throws Exception {
    var stateFile = tempDir.resolve("provision-state.yaml");
    var setupTracker = new ProvisionTracker<>(ProjectPhase.class, stateFile, false);
    setupTracker.load();
    setupTracker.advance(ProjectPhase.SSH_CONFIGURED);

    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab");
    var steps = new ArrayList<String>();
    var tracker = new ProvisionTracker<>(ProjectPhase.class, stateFile, false);
    var provisioner = new ProjectProvisioner(shell, tracker, new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertEquals(29, steps.size());
    assertTrue(steps.get(0).contains("skipped:1/"));
    assertTrue(steps.get(5).contains("skipped:6/"));
    assertTrue(steps.get(6).contains("step:7/"));
  }

  @Test
  void resumeFromCompleteSkipsAllSteps() throws Exception {
    var stateFile = tempDir.resolve("provision-state.yaml");
    var setupTracker = new ProvisionTracker<>(ProjectPhase.class, stateFile, false);
    setupTracker.load();
    setupTracker.advance(ProjectPhase.COMPLETE);

    var shell = new ScriptedShellExecutor(new ShellExec.Result(0, "", ""));
    var steps = new ArrayList<String>();
    var tracker = new ProvisionTracker<>(ProjectPhase.class, stateFile, false);
    var provisioner = new ProjectProvisioner(shell, tracker, new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertEquals(20, steps.size());
    assertTrue(steps.stream().allMatch(s -> s.startsWith("skipped:")));
  }

  @Test
  void launchFailureRecordsErrorInTracker() {
    var shell =
        new ScriptedShellExecutor()
            .onFail("incus info acme-health", "not found")
            .onFail("incus launch", "permission denied");
    var tracker = tracker();

    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(fullConfig(), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to launch container"));

    var state = tracker.currentState();
    assertNotNull(state.error());
    assertEquals("CONTAINER_LAUNCHED", state.error().failedPhase());
    assertTrue(state.error().message().contains("permission denied"));
  }

  @Test
  void existingContainerIsIdempotent() throws Exception {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onOk("incus info acme-health", "Name: acme-health\nStatus: RUNNING")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertTrue(steps.stream().anyMatch(s -> s.contains("done:1/") && s.contains("already exists")));
    var cmds = shell.invocations();
    assertFalse(cmds.stream().anyMatch(c -> c.contains("incus launch")));
  }

  @Test
  void projectImageOverridesHostImage() throws Exception {
    var shell = allSuccessShell();
    var customConfig =
        new SailYaml(
            "acme-health",
            "Acme Health",
            new SailYaml.Resources(4, "12GB", "150GB"),
            "ubuntu/22.04",
            List.of("postgresql-client-16"),
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));

    var provisioner = new ProjectProvisioner(shell, tracker(), null);
    provisioner.provision(customConfig, hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("incus launch ubuntu-22.04")),
        "Should use project image ubuntu-22.04, not host default");
  }

  @Test
  void nullProjectImageFallsBackToHostImage() throws Exception {
    var shell = minimalSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(minimalConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("incus launch ubuntu-24.04")),
        "Should fall back to host image ubuntu/24.04 → ubuntu-24.04");
  }

  @Test
  void diskQuotaSetCorrectly() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("size=150GB")), "Should set disk quota to 150GB");
  }

  @Test
  void resourceLimitsSetCorrectly() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("limits.cpu=4") && c.contains("limits.memory=12GB")),
        "Should set CPU and memory limits");
  }

  @Test
  void diskQuotaFailureRecordsError() {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onFail("incus config device override", "no such device");
    var tracker = tracker();

    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(fullConfig(), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to set disk quota"));
    assertEquals("DISK_QUOTA_SET", tracker.currentState().error().failedPhase());
  }

  @Test
  void resourceLimitsFailureRecordsError() {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("incus config device override")
            .onFail("incus config set", "limits not supported");
    var tracker = tracker();

    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(fullConfig(), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to set resource limits"));
    assertEquals("RESOURCE_LIMITS_SET", tracker.currentState().error().failedPhase());
  }

  @Test
  void networkTimeoutRecordsFailure() {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onFail("ip -4 addr show", "");
    var tracker = tracker();

    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(fullConfig(), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("network did not come up"));
    assertEquals("NETWORK_READY", tracker.currentState().error().failedPhase());
  }

  @Test
  void packageInstallFailureRecordsError() {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onOk("apt-get update")
            .onFail("apt-get install", "E: Unable to locate package");
    var tracker = tracker();

    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(fullConfig(), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to install packages"));
    assertEquals("PACKAGES_INSTALLED", tracker.currentState().error().failedPhase());
  }

  @Test
  void installPackagesIncludesBaselineAndUserPackages() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    var installCmd =
        cmds.stream().filter(c -> c.contains("apt-get install")).findFirst().orElseThrow();
    assertTrue(installCmd.contains("curl"));
    assertTrue(installCmd.contains("wget"));
    assertTrue(installCmd.contains("git"));
    assertTrue(installCmd.contains("sudo"));
    assertTrue(installCmd.contains("openssh-server"));
    assertTrue(installCmd.contains("postgresql-client-16"));
  }

  @Test
  void sshConfigCreatesUserAndKeys() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(cmds.stream().anyMatch(c -> c.contains("useradd") && c.contains("dev")));
    assertTrue(cmds.stream().anyMatch(c -> c.contains("usermod") && c.contains("sudo")));
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains("incus file push")
                        && c.contains("--mode 0440")
                        && c.contains("sudoers")),
        "sudoers pushed with mode 0440");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("incus file push") && c.contains("authorized_keys")),
        "authorized_keys written via file push");
    assertTrue(cmds.stream().anyMatch(c -> c.contains("chmod 700")));
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains("incus file push")
                        && c.contains("--mode 0600")
                        && c.contains("authorized_keys")),
        "authorized_keys pushed with mode 0600");
    assertTrue(cmds.stream().anyMatch(c -> c.contains("chown") && c.contains("dev:dev")));
    assertTrue(cmds.stream().anyMatch(c -> c.contains("systemctl enable --now ssh")));
  }

  @Test
  void userCreateFailureRecordsError() {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onFail("useradd", "useradd: permission denied");
    var tracker = tracker();

    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(fullConfig(), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to create user"));
    assertEquals("SSH_CONFIGURED", tracker.currentState().error().failedPhase());
  }

  @Test
  void sshNullConfigSkipsStep() throws Exception {
    var shell = minimalSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(minimalConfig(), hostYaml(), null, null);

    assertTrue(steps.stream().anyMatch(s -> s.contains("done:6/") && s.contains("skipped")));
    var cmds = shell.invocations();
    assertFalse(cmds.stream().anyMatch(c -> c.contains("useradd")));
  }

  @Test
  void existingUserNotRecreated() throws Exception {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onOk("id dev", "uid=1000(dev)")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab");
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertFalse(cmds.stream().anyMatch(c -> c.contains("useradd")));
  }

  @Test
  void sshWithEmptyKeysSkipsAuthorizedKeysSetup() throws Exception {
    var configWithEmptyKeys =
        new SailYaml(
            "acme-health",
            "Acme Health",
            new SailYaml.Resources(4, "12GB", "150GB"),
            "ubuntu/24.04",
            List.of("postgresql-client-16"),
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            new SailYaml.Ssh("dev", List.of()));
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("crontab -l", "no crontab");
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(configWithEmptyKeys, hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(cmds.stream().anyMatch(c -> c.contains("useradd")));
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains("authorized_keys")),
        "Should skip authorized_keys when key list is empty");
  }

  @Test
  void sshWithNullKeysSkipsAuthorizedKeysSetup() throws Exception {
    var configWithNullKeys =
        new SailYaml(
            "acme-health",
            "Acme Health",
            new SailYaml.Resources(4, "12GB", "150GB"),
            "ubuntu/24.04",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            new SailYaml.Ssh("dev", null));
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("crontab -l", "no crontab");
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(configWithNullKeys, hostYaml(), null, null);

    var cmds = shell.invocations();
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains("authorized_keys")),
        "Should skip authorized_keys when key list is null");
  }

  @Test
  void podmanInstalledAndSocketEnabled() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("apt-get install") && c.contains("podman")),
        "Should install podman via apt");
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains("incus file push")
                        && c.contains("--mode 0644")
                        && c.contains("01-unqualified.conf")),
        "Should push registries config with mode 0644");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("loginctl enable-linger dev")),
        "Should enable linger for dev user");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("systemctl --user enable --now podman.socket")),
        "Should enable podman socket");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("systemctl --user enable podman-restart")),
        "Should enable podman-restart for auto-start on boot");
  }

  @Test
  void podmanRestartFallbackCreatesServiceFile() throws Exception {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onceOnFail(
                "systemctl --user enable podman-restart", "Unit podman-restart.service not found")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab");
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream()
            .anyMatch(c -> c.contains("incus file push") && c.contains("podman-restart.service")),
        "Should push podman-restart.service file as fallback");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("systemctl --user daemon-reload")),
        "Should daemon-reload after creating service file");
  }

  @Test
  void podmanAlreadyInstalledSkipsAptInstall() throws Exception {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onOk("which podman", "/usr/bin/podman")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab");
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertFalse(
        cmds.stream()
            .anyMatch(
                c -> c.contains("apt-get install") && c.contains("podman") && c.contains("-qq")),
        "Should skip apt install when podman is already present");
    assertTrue(cmds.stream().anyMatch(c -> c.contains("loginctl enable-linger")));
    assertTrue(cmds.stream().anyMatch(c -> c.contains("podman.socket")));
  }

  @Test
  void podmanInstallFailureRecordsError() {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("apt-get install -y -qq podman", "E: Unable to locate package podman");
    var tracker = tracker();

    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(fullConfig(), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to install Podman"));
    assertEquals("PODMAN_INSTALLED", tracker.currentState().error().failedPhase());
  }

  @Test
  void testcontainersEnvConfigured() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains("incus file push")
                        && c.contains("--mode 0644")
                        && c.contains("testcontainers.sh")),
        "Should push testcontainers.sh with mode 0644");
  }

  @Test
  void testcontainersAlreadyConfiguredSkips() throws Exception {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onOk("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:8/") && s.contains("already configured")));
  }

  @Test
  void jdkInstalledViaAdoptium() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("adoptium.net/artifactory/api/gpg/key/public")),
        "Should add Adoptium GPG key");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("incus file push") && c.contains("adoptium.list")),
        "Should push Adoptium apt source list");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("apt-get install") && c.contains("temurin-25-jdk")),
        "Should install temurin-25-jdk");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("incus file push") && c.contains("jdk-env.sh")),
        "Should push JAVA_HOME profile script");
  }

  @Test
  void jdkSkippedWhenNoRuntimes() throws Exception {
    var shell = minimalSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(minimalConfig(), hostYaml(), null, null);

    assertTrue(steps.stream().anyMatch(s -> s.contains("skipped:9/") && s.contains("no JDK")));
    var cmds = shell.invocations();
    assertFalse(cmds.stream().anyMatch(c -> c.contains("temurin")));
  }

  @Test
  void jdkAlreadyInstalledSkips() throws Exception {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onOk("dpkg -s temurin-25-jdk", "Status: install ok installed")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:9/") && s.contains("already installed")));
  }

  @Test
  void jdkInstallFailureRecordsError() {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("apt-get install -y -qq temurin-25-jdk", "E: Unable to locate package");
    var tracker = tracker();

    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(fullConfig(), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to install temurin-25-jdk"));
    assertEquals("JDK_INSTALLED", tracker.currentState().error().failedPhase());
  }

  @Test
  void nodeInstalledViaNodeSource() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("deb.nodesource.com/setup_22")),
        "Should run NodeSource setup for version 22");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("apt-get install") && c.contains("nodejs")),
        "Should install nodejs");
  }

  @Test
  void nodeSkippedWhenNoRuntimes() throws Exception {
    var shell = minimalSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(minimalConfig(), hostYaml(), null, null);

    assertTrue(steps.stream().anyMatch(s -> s.contains("skipped:10/") && s.contains("no Node")));
  }

  @Test
  void nodeAlreadyInstalledSkips() throws Exception {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onOk("node --version", "v22.3.0")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:10/") && s.contains("already installed")));
  }

  @Test
  void nodeInstallFailureRecordsError() {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("apt-get install -y -qq nodejs", "E: Unable to locate package");
    var tracker = tracker();

    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(fullConfig(), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to install Node.js"));
    assertEquals("NODE_INSTALLED", tracker.currentState().error().failedPhase());
  }

  private static SailYaml configWithGit(String auth) {
    return new SailYaml(
        "acme-health",
        "Acme Health Platform",
        new SailYaml.Resources(4, "12GB", "150GB"),
        "ubuntu/24.04",
        null,
        null,
        new SailYaml.Git("Acme Eng", "eng@acme.com", auth, null),
        null,
        null,
        null,
        null,
        null,
        new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));
  }

  /** Shell setup that succeeds through step 10 (Node skipped) for configs without JDK/Node. */
  private ScriptedShellExecutor shellThroughStep10() {
    return new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
        .onFail("incus info acme-health", "not found")
        .onOk("incus launch")
        .onOk("ip -4 addr show")
        .onFail("id dev", "no such user")
        .onOk("useradd")
        .onFail("which podman", "")
        .onFail("test -f /etc/profile.d/testcontainers.sh", "")
        .onFail("crontab -l", "no crontab");
  }

  @Test
  void gitConfiguredWithTokenSetsCredentials() throws Exception {
    var shell = shellThroughStep10();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(configWithGit("token"), hostYaml(), Map.of("*", "ghp_test123"), null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream()
            .anyMatch(c -> c.contains("git config --global user.name") && c.contains("Acme Eng")),
        "Should set git user.name");
    assertTrue(
        cmds.stream()
            .anyMatch(
                c -> c.contains("git config --global user.email") && c.contains("eng@acme.com")),
        "Should set git user.email");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("ssh-keyscan")),
        "Should add known hosts for github/gitlab");
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains("incus file push")
                        && c.contains("--mode 0600")
                        && c.contains(".git-credentials")),
        "Should write .git-credentials via file push with mode 0600");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("git config --global credential.helper store")),
        "Should configure credential helper store");
  }

  @Test
  void gitConfiguredWithSshSkipsCredentialStore() throws Exception {
    var shell = shellThroughStep10();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(configWithGit("ssh"), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("git config --global user.name")),
        "Should still set git identity");
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains(".git-credentials")),
        "Should NOT write .git-credentials for ssh auth");
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains("credential.helper")),
        "Should NOT configure credential.helper for ssh auth");
  }

  @Test
  void gitSkippedWhenNoGitBlock() throws Exception {
    var shell = minimalSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(minimalConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("skipped:11/") && s.contains("no git")),
        "Step 11 should be skipped when git config is null");
    var cmds = shell.invocations();
    assertFalse(cmds.stream().anyMatch(c -> c.contains("git config --global")));
  }

  @Test
  void gitKnownHostsScansDefaultHosts() throws Exception {
    var shell = shellThroughStep10();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(configWithGit("token"), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream()
            .anyMatch(c -> c.contains("ssh-keyscan") && c.contains("github.com gitlab.com")),
        "Should scan default hosts (github.com, gitlab.com) via ssh-keyscan");
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains("ssh-keyscan -H github.com gitlab.com")),
        "ssh-keyscan hosts must be passed as positional arguments, not interpolated into shell");
  }

  @Test
  void gitTokenWithNullTokenSkipsCredentialStore() throws Exception {
    var shell = shellThroughStep10();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(configWithGit("token"), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("git config --global user.name")),
        "Should still set git identity even without token");
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains(".git-credentials")),
        "Should NOT write credentials when token is null");
    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:11/")),
        "Step 11 should complete successfully");
  }

  @Test
  void gitSshKeyPushedIntoContainer() throws Exception {
    var keyFile = tempDir.resolve("id_ed25519");
    Files.writeString(
        keyFile, "-----BEGIN OPENSSH PRIVATE KEY-----\nfake\n-----END OPENSSH PRIVATE KEY-----\n");
    var pubFile = tempDir.resolve("id_ed25519.pub");
    Files.writeString(pubFile, "ssh-ed25519 AAAA... test@host");

    var shell = shellThroughStep10();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    var config = configWithGitSshKey(keyFile.toString());
    provisioner.provision(config, hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains("incus file push")
                        && c.contains("--mode 0600")
                        && c.contains("id_ed25519")),
        "Should push private key with mode 0600");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("id_ed25519.pub")),
        "Should push public key when .pub file exists alongside private key");
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains(".git-credentials")),
        "Should NOT write .git-credentials for ssh auth");
  }

  @Test
  void gitSshKeyMissingThrowsClearError() {
    var shell = shellThroughStep10();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    var config = configWithGitSshKey("/nonexistent/path/id_ed25519");
    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(config, hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("SSH key not found"));
    assertTrue(ex.getMessage().contains("git.ssh_key"));
  }

  private static SailYaml configWithGitSshKey(String keyPath) {
    return new SailYaml(
        "acme-health",
        "Acme Health Platform",
        new SailYaml.Resources(4, "12GB", "150GB"),
        "ubuntu/24.04",
        null,
        null,
        new SailYaml.Git("Acme Eng", "eng@acme.com", "ssh", keyPath),
        null,
        null,
        null,
        null,
        null,
        new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));
  }

  private static SailYaml configWithMaven(String mavenVersion) {
    return new SailYaml(
        "acme-health",
        "Acme Health Platform",
        new SailYaml.Resources(4, "12GB", "150GB"),
        "ubuntu/24.04",
        null,
        new SailYaml.Runtimes(0, null, mavenVersion),
        null,
        null,
        null,
        null,
        null,
        null,
        new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));
  }

  @Test
  void mavenInstalledFromApacheCdn() throws Exception {
    var shell = shellThroughStep10().onFail("/opt/maven/bin/mvn --version", "No such file");
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(configWithMaven("3.9.9"), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains("dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9")),
        "Should download Maven 3.9.9 from Apache CDN");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("ln -sfn /opt/apache-maven-3.9.9 /opt/maven")),
        "Should create symlink");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("incus file push") && c.contains("maven-env.sh")),
        "Should push Maven environment script");
  }

  @Test
  void mavenFallsBackToApacheArchiveWhenCdnMisses() throws Exception {
    var shell =
        shellThroughStep10()
            .onFail("/opt/maven/bin/mvn --version", "No such file")
            .onceOnFail("dlcdn.apache.org/maven/maven-3/3.9.12", "curl: (22) 404 Not Found")
            .onOk("archive.apache.org/dist/maven/maven-3/3.9.12");
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(configWithMaven("3.9.12"), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains(
                        "dlcdn.apache.org/maven/maven-3/3.9.12/binaries/apache-maven-3.9.12")),
        "Should try the Apache CDN first");
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains(
                        "archive.apache.org/dist/maven/maven-3/3.9.12/binaries/apache-maven-3.9.12")),
        "Should fall back to the Apache archive");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("ln -sfn /opt/apache-maven-3.9.12 /opt/maven")),
        "Should create symlink after archive fallback succeeds");
  }

  @Test
  void mavenSkippedWhenNotRequested() throws Exception {
    var shell = minimalSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(minimalConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("skipped:12/") && s.contains("no Maven")),
        "Step 12 should be skipped when maven is null");
  }

  @Test
  void mavenAlreadyInstalledSkips() throws Exception {
    var shell =
        shellThroughStep10().onOk("/opt/maven/bin/mvn --version", "Apache Maven 3.9.9 (abc123)");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(configWithMaven("3.9.9"), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:12/") && s.contains("already installed")),
        "Should skip when correct Maven version is already installed");
    var cmds = shell.invocations();
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains("dlcdn.apache.org")),
        "Should NOT download when already installed");
  }

  @Test
  void mavenInstallFailureRecordsError() {
    var shell =
        shellThroughStep10()
            .onFail("/opt/maven/bin/mvn --version", "No such file")
            .onFail("dlcdn.apache.org/maven/maven-3/99.0.0", "curl: (22) 404 Not Found")
            .onFail("archive.apache.org/dist/maven/maven-3/99.0.0", "curl: (22) 404 Not Found");
    var tracker = tracker();
    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class,
            () -> provisioner.provision(configWithMaven("99.0.0"), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to install Maven"));
    assertTrue(ex.getMessage().contains("dlcdn.apache.org"));
    assertTrue(ex.getMessage().contains("archive.apache.org"));
    assertEquals("MAVEN_INSTALLED", tracker.currentState().error().failedPhase());
  }

  private static SailYaml configWithRepos(List<SailYaml.Repo> repos) {
    return new SailYaml(
        "acme-health",
        "Acme Health Platform",
        new SailYaml.Resources(4, "12GB", "150GB"),
        "ubuntu/24.04",
        null,
        null,
        null,
        repos,
        null,
        null,
        null,
        null,
        new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));
  }

  @Test
  void reposClonedAsDevUser() throws Exception {
    var repos =
        List.of(
            new SailYaml.Repo("https://github.com/acme/app.git", "acme", null),
            new SailYaml.Repo("https://github.com/acme/lib.git", "lib", null));
    var shell =
        shellThroughStep10()
            .onFail("test -d /home/dev/workspace/acme", "")
            .onFail("test -d /home/dev/workspace/lib", "");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(configWithRepos(repos), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains("git clone")
                        && c.contains("acme/app.git")
                        && c.contains("--user 1000")),
        "Should clone acme repo as dev user");
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains("git clone")
                        && c.contains("acme/lib.git")
                        && c.contains("--user 1000")),
        "Should clone lib repo as dev user");
    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:13/") && s.contains("2/2")),
        "Should report 2/2 repos cloned");
  }

  @Test
  void reposSkippedWhenNoneConfigured() throws Exception {
    var shell = minimalSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(minimalConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("skipped:13/") && s.contains("no repos")),
        "Step 13 should be skipped when repos is null");
  }

  @Test
  void repoAlreadyExistsIsSkipped() throws Exception {
    var repos = List.of(new SailYaml.Repo("https://github.com/acme/app.git", "acme", null));
    var shell = shellThroughStep10().onOk("test -d /home/dev/workspace/acme", "");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(configWithRepos(repos), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains("git clone")),
        "Should NOT clone when repo directory already exists");
    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:13/") && s.contains("0/1")),
        "Should report 0/1 repos cloned (existing skipped)");
  }

  @Test
  void repoWithBranchUsesBranchFlag() throws Exception {
    var repos = List.of(new SailYaml.Repo("https://github.com/acme/app.git", "acme", "develop"));
    var shell = shellThroughStep10().onFail("test -d /home/dev/workspace/acme", "");
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(configWithRepos(repos), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream()
            .anyMatch(c -> c.contains("git clone --branch develop") && c.contains("acme/app")),
        "Should use --branch flag when branch is specified");
  }

  @Test
  void repoCloneFailureThrows() {
    var repos = List.of(new SailYaml.Repo("https://github.com/acme/app.git", "acme", null));
    var shell =
        shellThroughStep10()
            .onFail("test -d /home/dev/workspace/acme", "")
            .onFail("git clone", "fatal: repository not found");
    var tracker = tracker();
    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class,
            () -> provisioner.provision(configWithRepos(repos), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to clone"));
    assertEquals("REPOS_CLONED", tracker.currentState().error().failedPhase());
  }

  @Test
  void workspaceFilesSkippedWhenSailYamlPathNull() throws Exception {
    var shell = allSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream()
            .anyMatch(s -> s.contains("skipped:14/") && s.contains("no files/ directory")));
  }

  @Test
  void workspaceFilesSkippedWhenNoFilesDirectory() throws Exception {
    var singYaml = tempDir.resolve("sail.yaml");
    java.nio.file.Files.writeString(singYaml, "name: test");

    var shell = allSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, singYaml);

    assertTrue(
        steps.stream()
            .anyMatch(s -> s.contains("skipped:14/") && s.contains("no files/ directory")));
  }

  @Test
  void workspaceFilesPushedWhenFilesDirectoryExists() throws Exception {
    var filesDir = tempDir.resolve("files");
    java.nio.file.Files.createDirectories(filesDir.resolve("outline"));
    java.nio.file.Files.writeString(filesDir.resolve("outline/.env"), "KEY=VALUE");
    java.nio.file.Files.writeString(filesDir.resolve("setup.sh"), "#!/bin/bash");
    var singYaml = tempDir.resolve("sail.yaml");
    java.nio.file.Files.writeString(singYaml, "name: test");

    var shell = allSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, singYaml);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:14/") && s.contains("2 workspace file(s)")));
    assertTrue(
        shell.invocations().stream()
            .anyMatch(
                c ->
                    c.contains("incus file push")
                        && c.contains("--uid 1000")
                        && c.contains("--gid 1000")
                        && c.contains("/home/dev/workspace/")));
    assertTrue(
        shell.invocations().stream()
            .anyMatch(
                c ->
                    c.contains("incus file push")
                        && c.contains("setup.sh")
                        && c.contains("--mode 0755")),
        "Shell scripts should be pushed with --mode 0755");
    assertTrue(
        shell.invocations().stream()
            .anyMatch(
                c ->
                    c.contains("incus file push")
                        && c.contains(".env")
                        && !c.contains("--mode 0755")),
        "Non-script files should not have --mode 0755");
  }

  @Test
  void workspaceFilesSkippedWhenFilesDirEmpty() throws Exception {
    java.nio.file.Files.createDirectories(tempDir.resolve("files"));
    var singYaml = tempDir.resolve("sail.yaml");
    java.nio.file.Files.writeString(singYaml, "name: test");

    var shell = allSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, singYaml);

    assertTrue(
        steps.stream()
            .anyMatch(s -> s.contains("skipped:14/") && s.contains("files/ directory is empty")));
  }

  @Test
  void servicesProvisionedViaPodmanRun() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream()
            .anyMatch(
                c ->
                    c.contains("podman run -d --restart=always --name postgres")
                        && c.contains("-p 5432:5432")
                        && c.contains("postgres:16")),
        "Should run postgres via podman run with correct flags");
  }

  @Test
  void servicesSkippedWhenNoneConfigured() throws Exception {
    var shell = minimalSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(minimalConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("skipped:15/") && s.contains("no services")));
  }

  @Test
  void serviceAlreadyExistsIsSkipped() throws Exception {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onOk("podman container inspect", "{}")
            .onFail("crontab -l", "no crontab");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertTrue(steps.stream().anyMatch(s -> s.contains("done:15/") && s.contains("0/1")));
    var cmds = shell.invocations();
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains("podman run")),
        "Should not run podman run for existing service");
  }

  @Test
  void serviceStartFailureRecordsError() {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("podman run", "Error: image not found");
    var tracker = tracker();

    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class, () -> provisioner.provision(fullConfig(), hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to start service 'postgres'"));
    assertEquals("SERVICES_PROVISIONED", tracker.currentState().error().failedPhase());
  }

  @Test
  void multipleServicesProvisionedInOrder() throws Exception {
    var services = new LinkedHashMap<String, SailYaml.Service>();
    services.put(
        "postgres", new SailYaml.Service("postgres:16", List.of(5432), Map.of(), null, null));
    services.put(
        "meilisearch",
        new SailYaml.Service("getmeili/meilisearch:latest", List.of(7700), Map.of(), null, null));
    var config =
        new SailYaml(
            "acme-health",
            "Multi-service",
            new SailYaml.Resources(4, "12GB", "150GB"),
            "ubuntu/24.04",
            null,
            null,
            null,
            null,
            services,
            null,
            null,
            null,
            new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(config, hostYaml(), null, null);

    var cmds = shell.invocations();
    var pgIdx = indexOfContaining(cmds, "--name postgres");
    var msIdx = indexOfContaining(cmds, "--name meilisearch");
    assertTrue(pgIdx > 0 && msIdx > 0 && pgIdx < msIdx, "postgres before meilisearch");
    assertTrue(steps.stream().anyMatch(s -> s.contains("done:15/") && s.contains("2/2")));
  }

  @Test
  void pruneCronConfigured() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("crontab -u dev")),
        "Should install crontab for dev user");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("incus file push") && c.contains("sail-crontab.")),
        "Should push crontab via temp file");
  }

  @Test
  void pruneCronAlreadyConfiguredSkips() throws Exception {
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onOk("crontab -l", "0 * * * * /home/dev/.sail/cleanup-containers.sh >/dev/null 2>&1");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:16/") && s.contains("already configured")));
  }

  @Test
  void agentToolsDefaultsToTypeWhenInstallIsNull() throws Exception {
    var shell = allSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:17/") && s.contains("claude-code")),
        "Step 17 should install agent type when install list is null");
  }

  @Test
  void agentToolsSkippedWhenNoAgentConfig() throws Exception {
    var shell = minimalSuccessShell();
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(minimalConfig(), hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("skipped:17/") && s.contains("no agent")),
        "Step 17 should be skipped when agent config is null");
  }

  @Test
  void agentToolsAlreadyInstalledSkipsInstall() throws Exception {
    var configWithInstall =
        new SailYaml(
            "acme-health",
            "Acme Health",
            new SailYaml.Resources(4, "12GB", "150GB"),
            "ubuntu/24.04",
            null,
            new SailYaml.Runtimes(25, "22", null),
            null,
            null,
            Map.of(
                "postgres",
                new SailYaml.Service("postgres:16", List.of(5432), Map.of(), null, null)),
            null,
            new SailYaml.Agent(
                "claude-code",
                true,
                "sail/",
                true,
                List.of("claude-code"),
                Map.of(),
                null,
                null,
                null,
                null,
                null),
            null,
            new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab")
            .onOk("which claude", "/home/dev/.local/bin/claude");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(configWithInstall, hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:17/") && s.contains("0/1")),
        "Should report 0/1 tools (already installed)");
    var cmds = shell.invocations();
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains("claude.ai/install.sh")),
        "Should NOT run install when claude is already on PATH");
  }

  @Test
  void agentToolsInstallFailureRecordsError() {
    var configWithInstall =
        new SailYaml(
            "acme-health",
            "Acme Health",
            new SailYaml.Resources(4, "12GB", "150GB"),
            "ubuntu/24.04",
            null,
            new SailYaml.Runtimes(25, "22", null),
            null,
            null,
            Map.of(
                "postgres",
                new SailYaml.Service("postgres:16", List.of(5432), Map.of(), null, null)),
            null,
            new SailYaml.Agent(
                "claude-code",
                true,
                "sail/",
                true,
                List.of("claude-code"),
                Map.of(),
                null,
                null,
                null,
                null,
                null),
            null,
            new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("node --version", "not found")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab")
            .onFail("which claude", "")
            .onFail("claude.ai/install.sh", "Connection refused");
    var tracker = tracker();
    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IOException.class,
            () -> provisioner.provision(configWithInstall, hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("Failed to install agent CLI"));
    assertEquals("AGENT_TOOLS_INSTALLED", tracker.currentState().error().failedPhase());
  }

  @Test
  void npmAgentToolRequiresNodeValidation() {
    var configWithCodex =
        new SailYaml(
            "acme-health",
            "Acme Health",
            new SailYaml.Resources(4, "12GB", "150GB"),
            "ubuntu/24.04",
            null,
            null,
            null,
            null,
            null,
            null,
            new SailYaml.Agent(
                "codex",
                true,
                "sail/",
                true,
                List.of("codex"),
                Map.of(),
                null,
                null,
                null,
                null,
                null),
            null,
            new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("crontab -l", "no crontab")
            .onFail("which codex", "")
            .onFail("which node", "");
    var tracker = tracker();
    var provisioner = new ProjectProvisioner(shell, tracker, null);

    var ex =
        assertThrows(
            IllegalStateException.class,
            () -> provisioner.provision(configWithCodex, hostYaml(), null, null));
    assertTrue(ex.getMessage().contains("requires Node.js"));
    assertTrue(ex.getMessage().contains("codex"));
  }

  @Test
  void multipleAgentToolsInstalled() throws Exception {
    var configWithMultiple =
        new SailYaml(
            "acme-health",
            "Acme Health",
            new SailYaml.Resources(4, "12GB", "150GB"),
            "ubuntu/24.04",
            null,
            new SailYaml.Runtimes(0, "22", null),
            null,
            null,
            null,
            null,
            new SailYaml.Agent(
                "claude-code",
                true,
                "sail/",
                true,
                List.of("claude-code", "codex"),
                Map.of(),
                null,
                null,
                null,
                null,
                null),
            null,
            new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("node --version", "not found")
            .onFail("crontab -l", "no crontab")
            .onFail("which claude", "")
            .onFail("which codex", "")
            .onOk("which node", "/usr/bin/node");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(configWithMultiple, hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("done:17/") && s.contains("2/2")),
        "Should install 2/2 agent tools");
    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("claude.ai/install.sh")), "Should install claude");
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("@openai/codex")), "Should install codex via npm");
  }

  @Test
  void writeProjectStateUsesFilePush() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    assertTrue(
        cmds.stream().anyMatch(c -> c.contains("incus file push") && c.contains("project.yaml")),
        "project.yaml should be written via incus file push");
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains("echo") && c.contains("project.yaml")),
        "project.yaml should NOT use echo shell pattern");
  }

  @Test
  void devUserCommandsUseCorrectIncusFlags() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    var socketCmd =
        cmds.stream().filter(c -> c.contains("podman.socket")).findFirst().orElseThrow();
    assertTrue(socketCmd.contains("--user 1000"), "Should exec as UID 1000");
    assertTrue(socketCmd.contains("--group 1000"), "Should exec as GID 1000");
    assertTrue(socketCmd.contains("HOME=/home/dev"), "Should set HOME");
    assertTrue(socketCmd.contains("XDG_RUNTIME_DIR=/run/user/1000"), "Should set XDG_RUNTIME_DIR");

    var podmanRun = cmds.stream().filter(c -> c.contains("podman run")).findFirst().orElseThrow();
    assertTrue(podmanRun.contains("--user 1000"), "podman run should exec as dev user");
  }

  @Test
  void rootCommandsUseStandardExecPrefix() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    var aptCmd = cmds.stream().filter(c -> c.contains("apt-get update")).findFirst().orElseThrow();
    assertTrue(aptCmd.startsWith("incus exec acme-health --"));
    assertFalse(aptCmd.contains("--user 1000"), "apt-get should run as root, not dev user");
  }

  @Test
  void commandOrderingIsCorrect() throws Exception {
    var shell = allSuccessShell();
    var provisioner = new ProjectProvisioner(shell, tracker(), null);

    provisioner.provision(fullConfig(), hostYaml(), null, null);

    var cmds = shell.invocations();
    var launch = indexOfContaining(cmds, "incus launch");
    var diskSet = indexOfContaining(cmds, "incus config device override");
    var limitsSet = indexOfContaining(cmds, "incus config set");
    var aptUpdate = indexOfContaining(cmds, "apt-get update");
    var aptInstall = indexOfContaining(cmds, "apt-get install");
    var sshEnable = indexOfContaining(cmds, "systemctl enable --now ssh");
    var loginctlLinger = indexOfContaining(cmds, "loginctl enable-linger");
    var podmanRun = indexOfContaining(cmds, "podman run");

    assertTrue(launch < diskSet, "launch before disk quota");
    assertTrue(diskSet < limitsSet, "disk before limits");
    assertTrue(limitsSet < aptUpdate, "limits before apt-get");
    assertTrue(aptUpdate < aptInstall, "update before install");
    assertTrue(aptInstall < sshEnable, "install before ssh");
    assertTrue(sshEnable < loginctlLinger, "ssh before podman setup");
    assertTrue(loginctlLinger < podmanRun, "linger before podman run");
  }

  private static int indexOfContaining(List<String> list, String substring) {
    for (var i = 0; i < list.size(); i++) {
      if (list.get(i).contains(substring)) {
        return i;
      }
    }
    return -1;
  }

  @Test
  void contextGenerationSkipsExistingAgentFiles() throws Exception {
    var config =
        new SailYaml(
            "acme-health",
            "Acme Health",
            new SailYaml.Resources(4, "12GB", "150GB"),
            "ubuntu/24.04",
            null,
            new SailYaml.Runtimes(25, null, null),
            null,
            null,
            Map.of(
                "postgres",
                new SailYaml.Service("postgres:16", List.of(5432), Map.of(), null, null)),
            null,
            new SailYaml.Agent(
                "claude-code",
                true,
                "sail/",
                true,
                List.of("claude-code"),
                Map.of(),
                null,
                null,
                null,
                null,
                null),
            null,
            new SailYaml.Ssh("dev", List.of("ssh-ed25519 AAAA...")));
    var shell =
        new ScriptedShellExecutor(new ShellExec.Result(0, "", ""))
            .onFail("incus info acme-health", "not found")
            .onOk("incus launch")
            .onOk("ip -4 addr show")
            .onFail("id dev", "no such user")
            .onOk("useradd")
            .onFail("which podman", "")
            .onFail("test -f /etc/profile.d/testcontainers.sh", "")
            .onFail("dpkg -s temurin-25-jdk", "not installed")
            .onOk("echo $VERSION_CODENAME", "noble")
            .onFail("podman container inspect", "no such container")
            .onFail("crontab -l", "no crontab")
            .onOk("which claude", "/home/dev/.local/bin/claude")
            .onOk("ls -1", "claude.md\nREADME.md");
    var steps = new ArrayList<String>();
    var provisioner = new ProjectProvisioner(shell, tracker(), new RecordingListener(steps));

    provisioner.provision(config, hostYaml(), null, null);

    assertTrue(
        steps.stream().anyMatch(s -> s.contains("kept existing")),
        "Should report that existing CLAUDE.md was kept");
    var cmds = shell.invocations();
    assertFalse(
        cmds.stream().anyMatch(c -> c.contains("file push") && c.contains("CLAUDE.md")),
        "Should NOT push CLAUDE.md when repo already has claude.md");
  }

  /** Records all step events for assertion. */
  private record RecordingListener(List<String> events) implements ProvisionListener {
    @Override
    public void onStep(int step, int total, String description) {
      events.add("step:" + step + "/" + total + ":" + description);
    }

    @Override
    public void onStepDone(int step, int total, String detail) {
      events.add("done:" + step + "/" + total + ":" + detail);
    }

    @Override
    public void onStepSkipped(int step, int total, String detail) {
      events.add("skipped:" + step + "/" + total + ":" + detail);
    }
  }
}
