/*
 * Copyright (c) 2026 Standard Applied Intelligence Labs
 * SPDX-License-Identifier: MIT
 */

package ai.singlr.sail.api;

public enum ErrorCode {
  INVALID_REQUEST(422),
  INVALID_JSON(400),
  INVALID_MODE(422),
  INVALID_TAIL(422),
  INVALID_ROLE(422),
  MISSING_BEARER_TOKEN(401),
  INVALID_BEARER_TOKEN(403),
  AUTHENTICATION_FAILED(401),
  PASSKEY_NOT_CONFIGURED(503),
  FORBIDDEN(403),
  UNSUPPORTED_MEDIA_TYPE(415),
  REQUEST_TOO_LARGE(413),
  NOT_FOUND(404),
  CONFLICT(409),
  METHOD_NOT_ALLOWED(405),
  RATE_LIMITED(429),
  PRECONDITION_FAILED(412),
  PROJECT_DESCRIPTOR_NOT_FOUND(404),
  PROJECT_NOT_CREATED(404),
  PROJECT_STOPPED(409),
  CONTAINER_ERROR(500),
  CONTAINER_IP_UNAVAILABLE(503),
  SERVER_IP_NOT_CONFIGURED(503),
  SPEC_NOT_FOUND(404),
  SPEC_NOT_READY(409),
  NODE_HANDLE_UNSET(409),
  RUNS_ON_OTHER_NODE(403),
  RUN_NOT_FOUND(404),
  RUN_ON_OTHER_NODE(409),
  NOT_YOUR_SPEC(403),
  READ_ONLY_CREDENTIAL(403),
  FORBIDDEN_NOT_ASSIGNEE(403),
  FORBIDDEN_ADMIN_ONLY(403),
  AGENT_ALREADY_RUNNING(409),
  AGENT_STATUS_FAILED(500),
  AGENT_LOG_FAILED(500),
  AGENT_STOP_FAILED(500),
  AGENT_REPORT_FAILED(500),
  AGENT_LAUNCH_FAILED(500),
  SNAPSHOT_FAILED(500),
  BRANCH_CREATE_FAILED(500),
  PROJECT_LOAD_FAILED(500),
  COMMAND_FAILED(500),
  INTERNAL(500);

  private final int httpCode;

  ErrorCode(int httpCode) {
    this.httpCode = httpCode;
  }

  public int httpCode() {
    return httpCode;
  }

  public String code() {
    return name().toLowerCase();
  }
}
